# Generated by Django 3.1.7 on 2021-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='comparendera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nomagente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mañana', models.CharField(max_length=20)),
                ('tarde', models.CharField(max_length=40)),
                ('noche', models.CharField(max_length=40)),
            ],
        ),
    ]
